### ISSUE TITLE
m5/networking/resources.tf vpc nat bug

### ISSUE THREAD

**Issue by labrown** [ned1313/Deep-Dive-Terraform#16]
The m5/networking/resources.tf vpc resource has  `enable_nat_gateway = true` causing new NAT objects to be created when you run the `terraform plan -out config.tfplan` command.

https://github.com/ned1313/Deep-Dive-Terraform/blob/cbb63f59903425ce19279a177a48fbbf923761f6/m5/networking/resources.tf#L72

The same issue is in m5/networking2/resources.tf

https://github.com/ned1313/Deep-Dive-Terraform/blob/cbb63f59903425ce19279a177a48fbbf923761f6/m5/networking2/resources.tf#L76

**Comment by fabioaraujopt** [comment]
Yup, change it to false man!
