### ISSUE TITLE
module 2

### ISSUE THREAD

**Issue by yepyepyep4711** [ned1313/Deep-Dive-Terraform#3]
Hello,

can you please explain the line ' terraform init --var-file="..\\..\terraform.tfvars" ' ?
You do this in module 2 without explaining it (unless I missed it). It sounds like we need to provide this, but why at init? At the plan stage a little later, you mention it is included in the module, but it's not. I'm confused.

**Comment by yun14u** [comment]
This module is supposed to accompany Ned’s Pluralsight course.  You will understand why he executes that ‘terraform init’ if you subscribe to his course (Ned, great course !)

**Comment by yepyepyep4711** [comment]
> This module is supposed to accompany Ned’s Pluralsight course. You will understand why he executes that ‘terraform init’ if you subscribe to his course (Ned, great course !)

the question I'm asking *IS* because I'm doing that course...

**Comment by sanramo1** [comment]
> > This module is supposed to accompany Ned’s Pluralsight course. You will understand why he executes that ‘terraform init’ if you subscribe to his course (Ned, great course !)
> 
> the question I'm asking _IS_ because I'm doing that course...

Hey,
Could you find the reason why he used that line?
Thanks!

**Comment by yepyepyep4711** [comment]
> > > This module is supposed to accompany Ned’s Pluralsight course. You will understand why he executes that ‘terraform init’ if you subscribe to his course (Ned, great course !)
> > 
> > 
> > the question I'm asking _IS_ because I'm doing that course...
> 
> Hey,
> Could you find the reason why he used that line?
> Thanks!

Nope, sorry

**Comment by yepyepyep4711** [comment]
by the way, if you're dabbling in these topic and need an environment to play with, here's something you might find useful https://gitlab.com/GillesDO/DevOps2GO
I find working in a clean environment every time helps you produce consistent results

**Comment by sanramo1** [comment]
> > > > This module is supposed to accompany Ned’s Pluralsight course. You will understand why he executes that ‘terraform init’ if you subscribe to his course (Ned, great course !)
> > > 
> > > 
> > > the question I'm asking _IS_ because I'm doing that course...
> > 
> > 
> > Hey,
> > Could you find the reason why he used that line?
> > Thanks!
> 
> Nope, sorry



> by the way, if you're dabbling in these topic and need an environment to play with, here's something you might find useful https://gitlab.com/GillesDO/DevOps2GO
> I find working in a clean environment every time helps you produce consistent results

Searching here https://blog.gruntwork.io/an-introduction-to-terraform-f17df9c6d180, I found it's a way to declare the value of variables. I think the explanation from the article is quite useful.
Thanks for your help!

**Comment by yepyepyep4711** [comment]
Right. I now took a closer look again. It had been some time and I have learnt a bit in the meantime. 

The explanation is this:
You need to pass the keys to AWS somehow. Obviously, you don't want to include these in your repository. There are several ways to do that. What Ned chose to do is to write them down in a file called "terraform.tfvars" placed two levels up from the modules' code. This is further "up" than the root of this repository.

This results in Ned being able to use his keys with his repository without sharing these keys with the whole wide world as a result. It may also be the reason why he says the file is "included" with module2. It isn't really, but maybe he just forgot about the fact that he's the only one able to see it.
Now to the syntax question. Let's look at the line again: ' terraform init --var-file="..\..\terraform.tfvars" '
You do ' terraform init ' where your code is. In our case, in ' module2 '. Terraform will only look in that folder for files to use, so if you want to pass other files to it, you need to specify them at the init stage.
' --var-file="..\..\terraform.tfvars ' tells terraform to go two levels up from where it's currently running and look for in file called ' terraform.tfvars ' for variables to use.

I hope this helps.
I've used the project I mentioned earlier, https://gitlab.com/GillesDO/DevOps2GO to understand what Ned did. You can read the readme there for more details. The difference between the two repositories is that the files with the secrets in it (' secrets.auto.tfvars ' instead of ' terraform.tfvars ', but does the same thing) is in the project's root, so no parameters are needed at ' terraform init '. Ned probably put it higher up to be able to use one file for all modules.

**Comment by sanramo1** [comment]
Thanks, I didn't see it from that point of view, the fact that Ned wanted to keep his credentials hidden didn't cross my mind. As you said during the course I was a bit confuse because the missing file with the credentials too, I agree with you that he probably forgot about them.

I'll continue checking the info you sent, I appreciate it.
Thanks again

**Comment by ned1313** [comment]
This deals with the previous version of the course, and I am going to go ahead and close the issue.
