### ISSUE TITLE
Module 3 Issues

### ISSUE THREAD

**Issue by uprightvinyl** [ned1313/Deep-Dive-Terraform#5]
Spotted a few of issues when running through module 3;

1. backend.tf file included in folder for m3, but not shown in the Pluralsight video. Running terraform init with this file asks for a path to be provided for Consul. Presume this file has crept in from a later module, so I propose it is deleted.
2. jq needs to be installed to run junior_admin.sh. Suggest this pre-requisite is called out.
3. ImportCommands.txt in this repository includes id values, whereas these are not included in the course video. As these values will always be unique, should they be removed from the commands file?
4. When setting up the import commands, the video states the Private Route Table Association ID is not included in the output of junior_admin.sh, however this was shown in the output for me. Is this a discrepancy between the junior_admin.sh and the ps1 version? Or an updated version of the script which doesn't quite match the video?
5. Import commands fail on Mac using ZSH, as the ADDR needs to be encapsulated in "", otherwise zsh identifies the [] in the address as a file path (ref: https://github.com/ohmyzsh/ohmyzsh/issues/7894). e.g. "module.vpc.aws_subnet.public[2]".

**Comment by figurethingsout** [comment]
In addition to @uprightvinyl comments, line 37  in junior_admin.sh is missing ' ', i.e. 
--query 'RouteTables[0].RouteTableId'  --output text

**Comment by ned1313** [comment]
Working on this now:
* Removed backed.tf file from repo, thanks @repcsi for the PR
* Added command to install `jq` if it's missing
* Added quotes for import commands
* Removed route table ID references (they should not have been there)
* Not sure what I said in the video, but the route table association ID is def there in the output

**Comment by ned1313** [comment]
> 
> 
> In addition to @uprightvinyl comments, line 37 in junior_admin.sh is missing ' ', i.e.
> --query 'RouteTables[0].RouteTableId' --output text

I just ran through the whole sequence and it seems to work without changing commands.

**Comment by ned1313** [comment]
Tested and validated, looks like we're good on all issues. Thanks everyone for bringing it to my attention!
