### ISSUE TITLE
Module 6 - common_tags merge order incorrect?

### ISSUE THREAD

**Issue by edwinsummers** [ned1313/Deep-Dive-Terraform#6]
In Module 6 "Workspaces and Collaboration", the `locals` block in `resources.tf` for common_tags merges the tags in Consul with the `terraform.workspace` value.

```
common_tags = merge({
        Environment = terraform.workspace
      },
      jsondecode(data.consul_keys.networking.var.common_tags)
    )
```

However, Terraform's `merge` function [favors values later in the argument sequence if maps contain the same key](https://www.terraform.io/docs/configuration/functions/merge.html). Since the Consul data is listed last here, the "Environment" tag always contains the Consul value of "Production". Should `resources.tf` be changed so that `terraform.workspace` is the last argument to the `merge` function?

**Comment by ned1313** [comment]
Thanks for pointing this out! I have resolved the issue.
